let strip = neopixel.create(DigitalPin.P2, 24, NeoPixelMode.RGB)
strip.setBrightness(10)
let range = strip.range(0, 6)
range.showRainbow(1, 320)
let range2 = strip.range(8, 6)
range2.showRainbow(1, 320)
let range3 = strip.range(16, 6)
range3.showRainbow(1, 320)
serial.writeLine("Connected")
basic.forever(function () {
    strip.rotate(1)
    basic.pause(100)
    strip.show()
})
